import { AIModel } from './types';

export const defaultModels: AIModel[] = [
  {
    id: 'gpt-4-turbo',
    name: 'GPT-4 Turbo',
    provider: 'openai',
    description: 'The latest GPT-4 model with improved instruction following, accuracy and knowledge through April 2023.',
    apiKeyName: 'OPENAI_API_KEY',
    apiEndpoint: 'https://api.openai.com/v1/chat/completions',
    maxTokens: 4000,
    temperature: 0.7,
  },
  {
    id: 'gpt-3.5-turbo',
    name: 'GPT-3.5 Turbo',
    provider: 'openai',
    description: 'The latest GPT-3.5 Turbo model with improved instruction following.',
    apiKeyName: 'OPENAI_API_KEY',
    apiEndpoint: 'https://api.openai.com/v1/chat/completions',
    maxTokens: 4000,
    temperature: 0.7,
  },
  {
    id: 'claude-3-opus',
    name: 'Claude 3 Opus',
    provider: 'anthropic',
    description: 'Anthropic\'s most powerful model for highly complex tasks.',
    apiKeyName: 'ANTHROPIC_API_KEY',
    apiEndpoint: 'https://api.anthropic.com/v1/messages',
    maxTokens: 4000,
    temperature: 0.7,
  },
  {
    id: 'claude-3-sonnet',
    name: 'Claude 3 Sonnet',
    provider: 'anthropic',
    description: 'Anthropic\'s balanced model for a wide range of tasks.',
    apiKeyName: 'ANTHROPIC_API_KEY',
    apiEndpoint: 'https://api.anthropic.com/v1/messages',
    maxTokens: 4000,
    temperature: 0.7,
  },
  {
    id: 'gemini-2.0-flash',
    name: 'Gemini 2.0 Flash',
    provider: 'google',
    description: 'Google\'s latest high-performance model for fast, efficient inference with comparable quality to Pro.',
    apiKeyName: 'GOOGLE_API_KEY',
    apiEndpoint: 'https://generativelanguage.googleapis.com/v1/models/gemini-2.0-flash:generateContent',
    maxTokens: 4000,
    temperature: 0.7,
  },
  {
    id: 'deepseek-coder',
    name: 'DeepSeek Coder',
    provider: 'deepseek',
    description: 'DeepSeek\'s specialized model for code generation and understanding.',
    apiKeyName: 'DEEPSEEK_API_KEY',
    apiEndpoint: 'https://api.deepseek.com/v1/chat/completions',
    maxTokens: 4000,
    temperature: 0.7,
  },
  {
    id: 'mistral-large',
    name: 'Mistral Large',
    provider: 'mistral',
    description: 'Mistral\'s largest model for advanced reasoning and creativity.',
    apiKeyName: 'MISTRAL_API_KEY',
    apiEndpoint: 'https://api.mistral.ai/v1/chat/completions',
    maxTokens: 4000,
    temperature: 0.7,
  },
  {
    id: 'cohere-command',
    name: 'Cohere Command',
    provider: 'cohere',
    description: 'Cohere\'s most capable model for text understanding and generation.',
    apiKeyName: 'COHERE_API_KEY',
    apiEndpoint: 'https://api.cohere.ai/v1/generate',
    maxTokens: 4000,
    temperature: 0.7,
  },
]; 